kafka:
   image: spotify/kafka
   container_name: kafka
   environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
   hostname: kafka

es:
   image: elasticsearch:2.0
   container_name: es
   ports:
      - "9200:9200"

models:
   build: .
   external_links:
      - mysql:db
   ports:
      - "8001:8000"
   volumes:
      - ./app_models:/app
   command: "mod_wsgi-express start-server --reload-on-changes app_models/wsgi.py"

exp:
   build: .
   links:
      - models:models-api
      - kafka:kafka
      - es:es
   ports:
      - "8002:8000"
   volumes:
      - ./app_exp:/app
   command: "mod_wsgi-express start-server --reload-on-changes app_exp/wsgi.py"

web:
   build: .
   links:
      - exp:exp-api
   ports:
      - "8000:8000"
   volumes:
      - ./app_web:/app
   command: "mod_wsgi-express start-server --reload-on-changes app_web/wsgi.py"

batch:
   build: .
   links:
      - kafka:kafka
      - es:es
   ports:
      - "8003:8000"
   volumes:
      - ./app_batch:/app
   command: "python batch.py"